### ISSUE TITLE
production を作る

### ISSUE THREAD

**Issue by yucao24hours** [yucao24hours/elt2015#100]
リリースまでにやる

- [x] `git push heroku master`
- [x] `heroku run rake db:migrate --app hoge`
- [x] `heroku restart --app hoge`
- [x] Heroku 環境定数を入れる
  - [x] Basic 認証 username / pass
  - [x] Twitter consumer key / secret
  - [x] GitHub key / secret
- [x] Heroku を有料プランにあげる
- [x] VoteSetting モデルのインスタンスをひとつつくっておく

**Comment by tatsuo** [comment]
iPhone実機からログインして投票できるか確認する

**Comment by yucao24hours** [comment]
ところでアプリ名なにがいいかな？ `2015` というのは入れたくないきもちなので、 elt-tokyurb とかでいいかな。

**Comment by yucao24hours** [comment]
`https://elt-tokyu.herokuapp.com/`

**Comment by yucao24hours** [comment]
メモ：push するまえに `heroku addons:add heroku-postgresql` しないと `rake assets:precompile` で失敗する

**Comment by yucao24hours** [comment]
メモ：GitHub の callback URL は、URL の最後に `/` がないとなぜか redirect URL mismatch になってしまう（そこまでの URL が正しくても）。そのため、Application registration するときの URL の最後には必ず `/` をつける。

**Comment by tatsuo** [comment]
:clap:

**Comment by yucao24hours** [comment]
Twitter と GitHub アカウント共に、ログインできることを確認しました。

**Comment by yucao24hours** [comment]
あ、Heroku を有料プランにしていない

**Comment by yucao24hours** [comment]
挙げていたタスクはすべて完了しました :ok:
