### ISSUE TITLE
production の URL と、 QR コード（必要なら）と、アプリ使いかたスライドへの URL が書かれた紙を印刷する

### ISSUE THREAD

**Issue by yucao24hours** [yucao24hours/elt2015#103]
受付時に配ってもらう

**Comment by yucao24hours** [comment]
これいらないかなー。PC あるだろうし URL うてばよさそう。

**Comment by tatsuo** [comment]
シンプルなURLなのでいらないかなーと思います

いま気づいたけど、ツイッタとかでURL拡散して、会場にいない人が登録しちゃったらどうしようかな‥そこはもう信じるしかないか

**Comment by yucao24hours** [comment]
た、たしかに............!!!!!!!!!!!!!!!!!

**Comment by yucao24hours** [comment]
まあ、すべての利用者は GH アカウントで特定されるとはいえ、その場にいないのに「あの人に勝ってほしいから <3」とかって投票してきたりすると、めんどくさそうですね。。

**Comment by tatsuo** [comment]
結果発表後の編集とかもそうなんだけど、ある程度は信じる方に倒すしかないかなーと思ってます。
ip制限とかかけるとネットワーク持たないと思うし
あとは分かり次第管理画面で…

**Comment by yucao24hours** [comment]
そうですね。そこは遠慮なく :hocho: しようと思います :angel: 
ということでこちらは対応しないという方針で。
