### ISSUE TITLE
iPhone から GitHub ログインしようとするとアプリが落ちる

### ISSUE THREAD

**Issue by yucao24hours** [yucao24hours/elt2015#104]
「GitHub でログイン」を押して、認証をしたあとのコールバック URL がおかしい？？

**Comment by yucao24hours** [comment]
GitHub の developer application を新しく作りなおして、Key と Secret を登録しなおしてみる。

**Comment by tatsuo** [comment]
#100 の結果次第

**Comment by tatsuo** [comment]
twitter はいける

**Comment by tatsuo** [comment]
heroku に http://eltt.herokuapp.com/ で以下の設定でiPhoneから動くのを確認しました

![oauth_application_settings](https://cloud.githubusercontent.com/assets/44219/9449120/8bbfa73c-4adb-11e5-9dbe-329379b2d513.jpg)

**Comment by tatsuo** [comment]
@yucao24hours http://eltt.herokuapp.com/ にiPhoneからgithubでログインできるかためしてもらえるとうれしいです〜m(_ _)m

**Comment by yucao24hours** [comment]
@tatsuo ログインできました！！！

**Comment by yucao24hours** [comment]
https じゃだめだったってことかな？？

**Comment by yucao24hours** [comment]
（こことは関係ないかもだけど、上記アプリの 投票所にいくとアプリ落ちました）

**Comment by tatsuo** [comment]
https だとだめっぽいすね

**Comment by yucao24hours** [comment]
https から http にすると、スマホではサインインできるようになるけど、こんどは PC でサインイン後に redirect URL mismatch で落ちるようになりませんか..???
今のステージング、多分そうなっていると思います。

**Comment by tatsuo** [comment]
あー、ほんとだ…

**Comment by tatsuo** [comment]
http://eltt.herokuapp.com/
こっちでためしてもらってもいいすか

**Comment by yucao24hours** [comment]
> http://eltt.herokuapp.com/

今やってみたら、PC、スマホともにサインインできました！
ただ、投票所に行ったときにアプリ落ちたのですが、これはマイグレーションとか別の問題でしょうか..?（ログご確認いただけると助かります）

**Comment by tatsuo** [comment]
マイグレーションですmm

**Comment by yucao24hours** [comment]
ところで、なにをしたらうまくいくようになったのしょうか？

**Comment by tatsuo** [comment]
http と 最後の `/` かな

**Comment by yucao24hours** [comment]
ちょっと文脈がわからないので、「なにをどうする」という形式で教えていただけるとありがたいです :bow:

**Comment by tatsuo** [comment]
あー、すみません、今丁度書こうとしてたとこだったんですが、別のコメントみて、そっち書いてました :bow: 
![oauth_application_settings](https://cloud.githubusercontent.com/assets/44219/9513037/826b93a8-4cc5-11e5-93ab-9e1765cc065b.jpg)

**Comment by tatsuo** [comment]
https にすると iPhone から繋げず
最後の `/` がないとPCから繋げない
という結果になりました

**Comment by yucao24hours** [comment]
あれー、どっちもやってるのにステージングは PC だと落ちるような...

**Comment by yucao24hours** [comment]
すみません、時間ないのでまたあとで試してみますが、さいあく iPhone 対応をあきらめて、PC のみでお使いくださいというアナウンスにするという方針にもできると思うので、こちらのタスクの優先度はほかより低くていいかなと思っています。

**Comment by yucao24hours** [comment]
これ途中でしたね。。今回は、スマホ（iPhone）からの利用は諦めようと思います。
