### ISSUE TITLE
出品物編集画面に、画像 URL の編集用フォームがない

### ISSUE THREAD

**Issue by yucao24hours** [yucao24hours/elt2015#116]

**Comment by tatsuo** [comment]
https://github.com/yucao24hours/elt2015/pull/114
ここで直ってると思います @yucao24hours

**Comment by yucao24hours** [comment]
ありがとうございます！！よかった :pray: :sweat_drops:

**Comment by yucao24hours** [comment]
あとで確認して close します :cat:

**Comment by yucao24hours** [comment]
#114 に含まれていることを確認したので close します
