### ISSUE TITLE
出品物として、既に登録した出品物のデータを非表示にしたい。

### ISSUE THREAD

**Issue by yucao24hours** [yucao24hours/elt2015#36]
なぜなら、誤って登録してしまったり、アンチハラスメントポリシーに抵触するものをそのままにしておきたくないからだ。

**Comment by yucao24hours** [comment]
すでにその出品物に投票されていた票はどうする？

**Comment by yucao24hours** [comment]
さいあく、update でタイトルをマスクするとかで対応できるので必須ではない

**Comment by yucao24hours** [comment]
運営都合で「この出品物は非表示にしたい」というときは、rails c で disable フラグを true にするなどして出さないようにする。

**Comment by yucao24hours** [comment]
>すでにその出品物に投票されていた票はどうする？

非表示にするだけなので、dependent: destroy みたいなことはしなくていい

**Comment by yucao24hours** [comment]
なんだこの「出品物として」って...

**Comment by tatsuo** [comment]
(?_?)

**Comment by yucao24hours** [comment]
このストーリー、タイトルがひどい typo をしていてよくわかっていなかったけど、書いてある内容的にどう考えても #7 と dup しているように見える...
そちらでは 物理削除で対応する（事前にコピペでスプレッドシートなどに保存し、次回以降のトラブル防止等に使う）という方針になった。

**Comment by yucao24hours** [comment]
close します。もし不明な点などがあったら、再度 open してください (_ _)
