### ISSUE TITLE
料理好きとして、自分が作って持ってきた料理の写真を掲載したい

### ISSUE THREAD

**Issue by yucao24hours** [yucao24hours/elt2015#5]
なぜなら、見た目にもこだわっているので、それも評価してもらいたいからだ。
なぜなら、画像を載せることで、会場のどの料理かをひと目で認識してもらいやすくなるからだ。

**Comment by yucao24hours** [comment]
あとからでも写真を掲載できるようにしたい

**Comment by yucao24hours** [comment]
LT は、画像にあたるものがないので、ソーシャルアカウントのアバターを使う。

**Comment by tatsuo** [comment]
@yucao24hours 
んー、LTはGithub or twitter のアイコンでいいと思うけど
料理はどうしましょうねえ。置き場所考えるとS3とか使うのもアレな気がするので、画像のURL貼れるようにしますかねえ？？それを直接見れるようにしましょうかねえ(?_?)

**Comment by yucao24hours** [comment]
画像の URL を記載したら、それが読み込まれて（展開されて）アプリでそのまま見られるってことかな？？

**Comment by tatsuo** [comment]
そのイメージです
ツイッタとかで上げてもらって、そのURLを貼る

**Comment by yucao24hours** [comment]
「インターネット上で閲覧できる状態になっている URL であればなんでも展開される」っていうことであれば、それでいいとおもいます :exclamation: （アップロードする手段が特定のサービスに依存してしまうようなことがなければいいとおもう、ということ :bulb: ）

**Comment by tatsuo** [comment]
はい
