### ISSUE TITLE
出品者として、自分が出品したものの結果を一覧したい

### ISSUE THREAD

**Issue by yucao24hours** [yucao24hours/elt2015#67]
なぜなら、自分の出品したものがどんな評判だったか気になるからだ。
たくさん出品していると、ひとつずつチェックしないといけないので、一覧形式で出ていて欲しいからだ。

最終結果発表のあとに、`my/exhibit/` のテーブルに「得票数」と「もらったコメント」を出品物ごとに出す。

**Comment by tatsuo** [comment]
これがないと2票以下の人がもらったコメントを読むことができない
